import Head from 'next/head';
import Image from 'next/image';
import { useContextualRouting } from '../views/routes.views';
import Link from 'next/link';
import { PhoneTextField, useClient } from '../components';
import { forwardRef, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { findContextualRoute } from '../views/routes';
import { getPath, isPhoneFormat } from '../utils';
import { FileUploader } from '../components/FileUploader';
import { MuiTelInput } from 'mui-tel-input';
import { Grid, TextField } from '@mui/material';
import { getCountryCallingCode } from 'libphonenumber-js';

export default function Home(props) {

  const client = useClient();
  const { constructLink } = useContextualRouting();
  const [count, setCount] = useState(0);

  const [value, setValue] = useState(null);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/terms"><a>Home</a></Link>
      <br />
      <Link {...constructLink({ pathname: '/account/signin', query: { name: undefined } })}><a>Sign In</a></Link>
      <br />
      <Link {...constructLink('/account/signup')}><a>Sign Up</a></Link>
      <br />
      <Link {...constructLink('/account/password/change')}><a>Change Password</a></Link>
      <br />
      <Link {...constructLink('/account/verify')}><a>Verify Account</a></Link>
      <br />
      <br />
      <Link {...constructLink('/account/password/reset')}><a>Reset Password</a></Link>
      <br />
      <br />
      <Link {...constructLink('/payments/checkout/eeea8761-2077-4f08-951d-09924661a60e')}><a>Checkout Payment</a></Link>
      <br />
      <br />

      <main>
        {JSON.stringify(client.user)}
        <Grid container>
          <Grid item  xs={12}>
            <FileUploader />
          </Grid>
        </Grid>
        {value}
      </main>
    </div>
  )
}

