import Head from 'next/head';
import Image from 'next/image';
import { useContextualRouting } from '../views/routes.views';
import Link from 'next/link';
import { useClient } from '../components';
import { useState } from 'react';
import { findContextualRoute } from '../views/routes';
import { getPath } from '../utils';
import { FileUploader } from '../components/FileUploader';

export default function Home(props) {

  const client = useClient();
  const { constructLink } = useContextualRouting();
  const [count, setCount] = useState(0);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/terms"><a>Home</a></Link>
      <br />
      <Link {...constructLink({ pathname: '/account/signin', query: { name: undefined } })}><a>Sign In</a></Link>
      <br />
      <Link {...constructLink('/account/signup')}><a>Sign Up</a></Link>
      <br />
      <Link {...constructLink('/account/password/change')}><a>Change Password</a></Link>
      <br />
      <Link {...constructLink('/account/verify')}><a>Verify Account</a></Link>
      <br />
      <br />
      <Link {...constructLink('/account/password/reset')}><a>Reset Password</a></Link>
      <br />
      <br />

      <main>
        {JSON.stringify(client.user)}
        <FileUploader />
      </main>
    </div>
  )
}

